package client

import (
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/NicolasFerreras/REPL-Pokedex/internal/model"
)

type Client struct {
	BaseURL    model.Config
	HTTPClient *http.Client
}

func NewClient(baseURL string) *Client {
	return &Client{
		BaseURL: model.Config{
			PreviousURL: baseURL,
			NextURL:     baseURL,
		},
		HTTPClient: &http.Client{
			Timeout: time.Second * 10,
		},
	}
}

func (c *Client) GetLocationArea(url string) (*model.AutoGenerated, error) {
	resp, err := c.HTTPClient.Get(url)
	if err != nil {
		return nil, fmt.Errorf("failed to make GET request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("received non-200 response code: %d", resp.StatusCode)
	}

	var locationArea model.AutoGenerated
	err = json.NewDecoder(resp.Body).Decode(&locationArea)
	if err != nil {
		return nil, fmt.Errorf("failed to decode response body: %w", err)
	}

	return &locationArea, nil
}
